CREATE TABLE IF NOT EXISTS payments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  task_id INT NOT NULL,
  task_done_id INT NOT NULL UNIQUE,
  freelancer_id INT NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  status ENUM('Menunggu Kelulusan', 'Diluluskan', 'Telah Dibayar') NOT NULL DEFAULT 'Menunggu Kelulusan',
  remarks TEXT NULL,
  approved_by INT NULL,
  approved_at DATETIME NULL,
  paid_by INT NULL,
  paid_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_payments_task_id (task_id),
  INDEX idx_payments_task_done_id (task_done_id),
  INDEX idx_payments_freelancer_id (freelancer_id),
  INDEX idx_payments_status_created_at (status, created_at),
  CONSTRAINT fk_payments_task FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE,
  CONSTRAINT fk_payments_task_done FOREIGN KEY (task_done_id) REFERENCES task_done(id) ON DELETE CASCADE,
  CONSTRAINT fk_payments_freelancer FOREIGN KEY (freelancer_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_payments_approved_by FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_payments_paid_by FOREIGN KEY (paid_by) REFERENCES users(id) ON DELETE SET NULL
);
